#!/usr/bin/env python3
"""Enrich all cases with complete IC interview form data (all 11 wizard sections)."""
from pymongo import MongoClient

db = MongoClient()['cps_system_dev']

# ── Shorthand option strings (exact wizard option text) ──────────────────────
GA = {
    'neat':     'Neat and well-groomed – organized, clean, and appropriately dressed',
    'casual':   'Casually dressed – relaxed, informal attire',
    'disheveled':'Disheveled or unkempt – noticeably disorganized or poorly maintained appearance',
    'tense':    'Tense or rigid posture – stiff body language or noticeable physical guardedness',
    'relaxed':  'Relaxed and open body language – comfortable, natural posture',
    'distress': 'Notable physical signs of distress – shaking, nail-biting, or visible signs of anxiety',
    'tired':    'Tired or fatigued – appears sleep-deprived or low energy',
}
CS = {
    'clear':    'Clear and articulate – expresses thoughts clearly and fluently',
    'hesitant': 'Hesitant or guarded – pauses frequently or appears reluctant to share',
    'verbose':  'Verbose / overtalkative – provides excessive or tangential details',
    'minimal':  'Minimal responder – gives short, one-word, or limited responses',
    'expressive':'Emotionally expressive – regularly shows emotion in speech',
    'flat':     'Flat or monotone – little variation in tone or emotional expression',
}
GD = {
    'cooperative':'Cooperative and engaged – participates actively in the session',
    'resistant':  'Resistant or avoidant – reluctant to engage or discuss certain topics',
    'anxious':    'Anxious or apprehensive – visibly nervous or worried during the session',
    'sad':        'Sad or tearful – displays sadness; may cry during session',
    'calm':       'Calm and composed – maintains emotional regulation throughout',
    'friendly':   'Friendly and open – builds rapport easily, appears at ease',
    'suspicious': 'Suspicious or guarded – hesitant to trust or share openly',
}
PP = {
    'anxiety':     'Anxiety / worry – persistent anxiety, nervousness, or excessive worry',
    'depression':  'Depression / low mood – persistent sadness, low energy, or hopelessness',
    'academic':    'Academic concern – stress, poor performance, or difficulty managing academic load',
    'relationship':'Relationship concern – conflicts with peers, family, or romantic partner',
    'grief':       'Grief / loss – difficulty coping with loss or bereavement',
    'adjustment':  'Adjustment difficulties – challenges adapting to new environment or role',
    'identity':    'Identity concern – confusion or conflict around identity, values, or life direction',
    'self_esteem': 'Self-esteem concern – low confidence, self-doubt, or negative self-image',
    'trauma':      'Trauma – distressing experiences affecting daily life',
    'substance':   'Substance use – use of substances affecting academic or personal functioning',
    'career':      'Career / future concern – uncertainty or anxiety about career direction',
}
PH = {
    'past_exp':   'Significant past experiences – history of trauma, loss, illness, or major life transitions',
    'family':     'Family background – quality of family relationships, support, or sources of conflict',
    'coping':     'Coping styles and strategies – ways the client typically manages stress',
    'academic':   'Academic or work functioning – level of motivation, performance, or adjustment',
    'peers':      'Peer and social relationships – quality of friendships or social supports',
    'health':     'Health and lifestyle – physical well-being, sleep, exercise, nutrition, or medical conditions',
    'prev_tx':    'Previous counseling or therapy – prior experience with mental health services',
    'substance':  'Substance use history – use of alcohol, nicotine, caffeine, or other substances',
    'faith':      'Faith or spirituality – beliefs or practices that influence coping and meaning-making',
}
IR = {
    'engaged':    'Engaged and cooperative – open, responsive, and actively participated',
    'warm':       'Warm and receptive – friendly and comfortable engaging in dialogue',
    'guarded':    'Guarded or hesitant – cautious, reserved, or limited in responses',
    'calm':       'Calm and composed – steady demeanor and appropriate behavior',
    'withdrawn':  'Withdrawn or avoidant – quiet, minimal eye contact, or reluctant to engage',
    'irritable':  'Irritable or defensive – easily frustrated or resistant to feedback',
    'motivated':  'Motivated and hopeful – shows readiness and willingness to improve',
}
AE = {
    'appropriate':'Appropriate to content – emotion matches the topic being discussed',
    'anxious':    'Anxious / tense – fidgety, restless, or visibly nervous',
    'depressed':  'Depressed / sad – flat affect, tearful, or downcast tone',
    'irritable':  'Irritable / frustrated – easily annoyed or impatient',
    'labile':     'Labile / fluctuating – sudden shifts in mood or expression',
    'flat':       'Flat / restricted – limited range of emotion or monotone tone',
    'euthymic':   'Euthymic / stable – balanced, calm, and consistent emotional tone',
}
MP = {
    'avoidance':  'Avoidance behaviors – Tendency to avoid situations, tasks, or conversations that cause discomfort',
    'neg_self':   'Negative self-talk or self-criticism – Persistent self-blame, harsh internal dialogue, or low self-worth',
    'suppression':'Emotional suppression – Difficulty expressing or acknowledging emotions',
    'worry':      'Excessive worry or rumination – Repetitive overthinking, difficulty letting go',
    'perfectionism':'Perfectionism or fear of failure – Unrealistic standards, strong fear of making mistakes',
    'dependence': 'Dependence on others for reassurance – Difficulty making decisions or coping independently',
    'impulsivity':'Impulsivity or difficulty with emotional regulation – Acting quickly when distressed',
    'maladaptive_coping':'Maladaptive coping strategies – Coping styles that provide short-term relief but increase distress',
    'interpersonal':'Interpersonal difficulties – Recurrent conflicts, withdrawal, or difficulty setting boundaries',
    'trauma_resp':'Trauma-related responses – Hypervigilance, emotional numbing, or heightened reactivity',
    'academic_pat':'Academic/work-related maladaptive patterns – Procrastination, disengagement, or chronic burnout',
    'none':        'No maladaptive patterns identified at intake',
}
PRE = {
    'family_hx':  'Family history of mental health or relational problems',
    'early_adv':  'Early childhood adversity or trauma',
    'personality':'Personality traits (e.g., perfectionism, dependency, impulsivity)',
    'medical':    'Chronic medical condition or neurobiological vulnerability',
    'attachment': 'Limited early emotional support or attachment disruption',
    'cultural':   'Cultural, gender, or identity-related stress exposure',
}
PCI = {
    'loss':       'Recent loss or separation',
    'academic':   'Academic or work stress / overload',
    'relationship':'Relationship conflict or breakup',
    'transition': 'Transition or adjustment (e.g., relocation, new role, course changes)',
    'health':     'Health-related event or diagnosis',
    'trauma':     'Traumatic or critical incident',
}
PER = {
    'maladaptive':'Maladaptive coping (avoidance, withdrawal, substance use)',
    'stressors':  'Ongoing stressors (family, financial, workload)',
    'environment':'Environmental barriers (limited support, unsafe environment)',
    'neg_thinking':'Negative thinking patterns or self-criticism',
    'no_insight': 'Lack of insight or resistance to change',
    'self_care':  'Poor self-care or sleep habits',
}
PRO = {
    'social':     'Supportive relationships or social network',
    'faith':      'Faith or spirituality',
    'academic':   'Academic or work engagement',
    'motivation': 'Motivation to improve / willingness to seek help',
    'coping':     'Effective coping or problem-solving skills',
    'stable':     'Stable housing or financial situation',
    'resources':  'Access to mental health and community resources',
}
REC = {
    'continue':   'Continue Counseling / Psychotherapy – client to engage in ongoing sessions with same counselor/psychologist or team',
    'psych_test': 'Referral to CPS Psychologist (Testing / Assessment) – for further diagnostic or psychological evaluation',
    'psych_tx':   'Referral to CPS Psychologist for Psychotherapy – referred for specialized, in-depth therapy within CPS',
    'psychiatry': 'Referral to Psychiatrist / Physician – for medication evaluation or medical management',
    'crisis':     'Crisis Intervention / Safety Plan Initiated – immediate response to safety or suicide risk concerns',
    'collab':     'Collaboration with Faculty / Staff (with consent) – coordinate support for academic or behavioral concerns',
    'external':   'Referral to External Support / Agency – e.g., community mental health center, support group, or hotline',
    'follow_up':  'Follow-up Session Scheduled – next session date or frequency confirmed',
}

def g(*keys): return [GA[k] for k in keys]
def c(*keys): return [CS[k] for k in keys]
def d(*keys): return [GD[k] for k in keys]
def p(*keys): return [PP[k] for k in keys]
def h(*keys): return [PH[k] for k in keys]
def i(*keys): return [IR[k] for k in keys]
def a(*keys): return [AE[k] for k in keys]
def m(*keys): return [MP[k] for k in keys]
def pre(*keys): return [PRE[k] for k in keys]
def pci(*keys): return [PCI[k] for k in keys]
def per(*keys): return [PER[k] for k in keys]
def pro(*keys): return [PRO[k] for k in keys]
def rec(*keys): return [REC[k] for k in keys]

# ── Per-case enrichment data keyed by case_number ───────────────────────────
ENRICHMENTS = {
'CPS-2025-001': dict(  # Emma — academic stress/anxiety
    general_appearance=g('neat','relaxed'), communication_style=c('clear','expressive'),
    general_disposition=d('cooperative','anxious'),
    brief_description_remarks='Student arrived on time, well-groomed. Visible tension; picked at fingers during session. Relaxed progressively as rapport built.',
    presenting_problem=p('anxiety','academic'),
    presenting_problem_remarks='Reports escalating anxiety for the past 3 weeks linked to thesis deadlines. Experiences anticipatory worry, difficulty sleeping the night before submissions, and mental blanking during presentations.',
    psychosocial_history=h('academic','coping','peers'),
    psychosocial_remarks='Strong academic history; first time seeking counseling. Close friend group provides good social support. Primary coping has been avoidance and over-preparation. No prior mental health history.',
    interaction_relationship=i('engaged','warm'), affect_expression=a('appropriate','anxious'),
    interaction_remarks='Rapport established quickly. Student was forthcoming and engaged. Responded well to normalization of performance anxiety.',
    maladaptive_patterns=m('avoidance','worry','perfectionism'),
    counseling_goal='Within 8 sessions, client will demonstrate consistent use of at least two adaptive coping strategies (thought records and scheduled worry time) to reduce anxiety episodes from daily to 2–3×/week, as measured by weekly GAD-7 reassessment.',
    predisposing_factors=pre('personality'), precipitating_factors=pci('academic'),
    perpetuating_factors=per('neg_thinking','maladaptive'), protective_factors=pro('social','motivation','academic'),
    recommendation=rec('continue','follow_up')),

'CPS-2025-002': dict(  # Mark — depression/SI
    general_appearance=g('disheveled','tired'), communication_style=c('hesitant','minimal'),
    general_disposition=d('sad','resistant'),
    brief_description_remarks='Student appeared fatigued, poorly groomed. Slow gait. Sat with head down. Cried briefly when asked about academic performance.',
    presenting_problem=p('depression','self_esteem'),
    presenting_problem_remarks='Reports persistent low mood for 6 weeks, passive suicidal ideation (no plan or intent), social isolation, and anhedonia. PHQ-9: 22 — Severe range.',
    psychosocial_history=h('past_exp','family','coping'),
    psychosocial_remarks='Parental separation during high school; strained relationship with father. Previously coped through exercise and socializing — both now abandoned. No prior counseling or psychiatric history.',
    interaction_relationship=i('guarded','calm'), affect_expression=a('depressed','flat'),
    interaction_remarks='Initially resistant and monosyllabic. Opened up gradually as the IC normalized depressive experiences. Expressed relief at the end of session.',
    maladaptive_patterns=m('avoidance','neg_self','suppression'),
    counseling_goal='Within 12 sessions, client will reduce PHQ-9 score from 22 to below 10, maintain an active safety plan with zero crisis escalations, and demonstrate consistent behavioral activation (minimum 3 activities/week).',
    predisposing_factors=pre('family_hx','attachment'), precipitating_factors=pci('academic','relationship'),
    perpetuating_factors=per('stressors','self_care','neg_thinking'), protective_factors=pro('motivation','resources'),
    recommendation=rec('crisis','psychiatry','continue')),

'CPS-2025-003': dict(  # Lena — relationship issues/anxiety
    general_appearance=g('casual','tense'), communication_style=c('clear','expressive'),
    general_disposition=d('cooperative','sad'),
    brief_description_remarks='Student dressed casually, appeared physically tense. Maintained good eye contact. Teared up briefly when discussing breakup.',
    presenting_problem=p('anxiety','relationship','grief'),
    presenting_problem_remarks='Experiencing significant distress following a 2-year relationship ending 3 weeks ago. Reports sleep disturbance, difficulty concentrating, and intrusive memories of the relationship.',
    psychosocial_history=h('past_exp','family','peers','coping'),
    psychosocial_remarks='Generally good adjustment history. Close peer relationships. Parents are supportive but student avoids sharing emotional difficulties with them. Copes through overthinking and rumination.',
    interaction_relationship=i('engaged','warm'), affect_expression=a('appropriate','depressed'),
    interaction_remarks='Student was open and reflective. Demonstrated good self-awareness. Engaged actively in exploring feelings about the breakup.',
    maladaptive_patterns=m('worry','neg_self','suppression'),
    counseling_goal='Within 6 sessions, client will demonstrate adaptive grieving by identifying and expressing emotions without excessive rumination, improving sleep quality to 6+ hours nightly, and returning to previous academic functioning.',
    predisposing_factors=pre('personality'), precipitating_factors=pci('relationship','loss'),
    perpetuating_factors=per('neg_thinking','maladaptive'), protective_factors=pro('social','motivation','faith'),
    recommendation=rec('continue','follow_up')),

'CPS-2025-004': dict(  # Alec — academic pressure/perfectionism
    general_appearance=g('neat','relaxed'), communication_style=c('clear','verbose'),
    general_disposition=d('cooperative','anxious'),
    brief_description_remarks='Student was punctual and well-presented. Tendency to over-explain, providing extensive context for each answer. No signs of acute distress.',
    presenting_problem=p('academic','anxiety','self_esteem'),
    presenting_problem_remarks='Reports excessive self-criticism after receiving a B+ on a midterm, catastrophizing about academic standing. Fear of failure is interfering with academic engagement and enjoyment of learning.',
    psychosocial_history=h('academic','family','coping'),
    psychosocial_remarks='High-achieving academic background. Family expectations are high but generally supportive. Historically self-motivated but now driven by fear of failure rather than intrinsic motivation.',
    interaction_relationship=i('engaged','motivated'), affect_expression=a('appropriate','anxious'),
    interaction_remarks='Excellent engagement. Showed insight into perfectionism pattern when gently challenged. Expressed genuine motivation to change.',
    maladaptive_patterns=m('perfectionism','neg_self','worry'),
    counseling_goal='Within 8 sessions, client will distinguish self-worth from academic performance, apply self-compassion techniques when experiencing setbacks, and reduce avoidance of challenging academic tasks.',
    predisposing_factors=pre('personality'), precipitating_factors=pci('academic'),
    perpetuating_factors=per('neg_thinking','maladaptive'), protective_factors=pro('academic','motivation','social'),
    recommendation=rec('continue','follow_up')),

'CPS-2025-005': dict(  # Carla — career anxiety/life transition
    general_appearance=g('neat','casual'), communication_style=c('clear','expressive'),
    general_disposition=d('cooperative','anxious'),
    brief_description_remarks='Student was well-presented and articulate. Showed clear distress when discussing graduation and career decisions. Otherwise composed.',
    presenting_problem=p('career','anxiety','identity'),
    presenting_problem_remarks='Experiencing significant anxiety around post-graduation plans. Reports conflict between family expectations (nursing practice) and personal interest in arts therapy. Decision paralysis present.',
    psychosocial_history=h('family','academic','coping','faith'),
    psychosocial_remarks='Close-knit family with traditional values around career. Student is spiritually grounded. Coping through research and overthinking. Good peer support in clinical peers.',
    interaction_relationship=i('engaged','warm','motivated'), affect_expression=a('appropriate','anxious'),
    interaction_remarks='Student was self-aware and reflective. Showed relief when IC validated career ambivalence as a normal experience.',
    maladaptive_patterns=m('worry','avoidance','dependence'),
    counseling_goal='Within 6 sessions, client will identify core career values, articulate at least 2 viable career pathways aligned with those values, and demonstrate reduced anxiety around decision-making using structured decision frameworks.',
    predisposing_factors=pre('cultural','personality'), precipitating_factors=pci('transition','academic'),
    perpetuating_factors=per('stressors','neg_thinking'), protective_factors=pro('faith','social','motivation'),
    recommendation=rec('continue','follow_up')),

'CPS-2025-006': dict(  # Alex — severe depression/SI with plan
    general_appearance=g('disheveled','distress','tired'), communication_style=c('minimal','flat'),
    general_disposition=d('sad','resistant'),
    brief_description_remarks='Student appeared in significant distress — shaking hands, barely audible voice. Poorly groomed. Emergency protocol activated after SI with plan disclosed mid-session.',
    presenting_problem=p('depression','self_esteem'),
    presenting_problem_remarks='Disclosed SI with a specific plan (medication overdose). Reports hopelessness, feeling like a burden, and inability to see a future. PHQ-9: 27 — Severe. Crisis level presentation.',
    psychosocial_history=h('past_exp','family','coping'),
    psychosocial_remarks='History of depressive episodes. Ongoing family conflict. Lost a close friend to suicide one year ago. No prior counseling. Completely isolated socially for the past 2 months.',
    interaction_relationship=i('withdrawn','guarded'), affect_expression=a('depressed','flat'),
    interaction_remarks='Extremely limited engagement initially. Required multiple gentle prompts to disclose SI. Once disclosed, became tearful but expressed relief. Consent obtained for emergency contact.',
    maladaptive_patterns=m('avoidance','neg_self','trauma_resp','suppression'),
    counseling_goal='Immediate goal: safety stabilization. Within 4 weeks, client will adhere to safety plan daily, deny active SI with plan, engage with psychiatry, and attend minimum 2 sessions/week.',
    predisposing_factors=pre('family_hx','early_adv','attachment'), precipitating_factors=pci('loss','academic'),
    perpetuating_factors=per('neg_thinking','environment','no_insight'), protective_factors=pro('motivation','resources'),
    recommendation=rec('crisis','psychiatry','continue')),

'CPS-2025-007': dict(  # Miguel — trauma/PTSD
    general_appearance=g('casual','tense'), communication_style=c('hesitant','expressive'),
    general_disposition=d('anxious','cooperative'),
    brief_description_remarks='Student sat near the door and scanned the room on entry — hypervigilance noted. Startled twice by external sounds. Otherwise cooperative.',
    presenting_problem=p('trauma','anxiety'),
    presenting_problem_remarks='Flashbacks (3–4×/week), nightmares, and hypervigilance following a motor vehicle accident 2 months ago. Has completely stopped using public transportation. Academic attendance declining.',
    psychosocial_history=h('past_exp','academic','peers','health'),
    psychosocial_remarks='No prior mental health history. Previously high-functioning academically. Good family and peer support but has been withdrawing since the accident. Sleep severely disrupted.',
    interaction_relationship=i('engaged','guarded'), affect_expression=a('anxious','appropriate'),
    interaction_remarks='Student was willing to share but became visibly distressed when describing the accident. Required grounding before proceeding. Able to complete intake successfully.',
    maladaptive_patterns=m('avoidance','trauma_resp'),
    counseling_goal='Within 12 sessions using trauma-focused CBT and EMDR preparation, client will reduce PTSD symptom severity (PCL-5 from baseline to below 33), return to using public transport, and restore academic attendance.',
    predisposing_factors=pre('personality'), precipitating_factors=pci('trauma'),
    perpetuating_factors=per('maladaptive','stressors'), protective_factors=pro('social','motivation','academic'),
    recommendation=rec('psych_tx','continue','follow_up')),

'CPS-2025-008': dict(  # Ella — family conflict/stress
    general_appearance=g('neat','tense'), communication_style=c('clear','hesitant'),
    general_disposition=d('cooperative','anxious'),
    brief_description_remarks='Student was appropriately dressed. Initial hesitance about discussing family; became more open as session progressed. No acute distress signs.',
    presenting_problem=p('relationship','anxiety','academic'),
    presenting_problem_remarks='Chronic stress from ongoing parental conflict at home. Parents arguing frequently since financial difficulties began. Student reports difficulty concentrating and intrusive thoughts about family during classes.',
    psychosocial_history=h('family','academic','coping','peers'),
    psychosocial_remarks='Home environment has been tense for approximately 6 months. Student is the eldest child and feels pressure to mediate. Academic performance remains adequate but declining. Friends unaware of home situation.',
    interaction_relationship=i('engaged','calm'), affect_expression=a('appropriate','anxious'),
    interaction_remarks='Student was thoughtful and engaged. Showed genuine insight into the impact of family stress on their functioning. Expressed relief that these feelings were taken seriously.',
    maladaptive_patterns=m('suppression','worry','avoidance'),
    counseling_goal='Within 8 sessions, client will develop and consistently apply 3 emotional regulation strategies during family conflict situations, maintain academic performance, and establish appropriate emotional distance from parental conflicts.',
    predisposing_factors=pre('family_hx'), precipitating_factors=pci('relationship','academic'),
    perpetuating_factors=per('stressors','environment'), protective_factors=pro('social','academic','motivation'),
    recommendation=rec('continue','follow_up')),

'CPS-2025-009': dict(  # Fred — burnout/academic exhaustion
    general_appearance=g('casual','tired'), communication_style=c('hesitant','flat'),
    general_disposition=d('cooperative','resistant'),
    brief_description_remarks='Student appeared noticeably fatigued. Flat affect initially. Engaged more as session progressed. No acute crisis signs.',
    presenting_problem=p('academic','depression'),
    presenting_problem_remarks='Reports emotional exhaustion, loss of motivation, and detachment from studies after years of high academic demands. States "I know I should care but I don\'t feel anything about it anymore."',
    psychosocial_history=h('academic','coping','health','peers'),
    psychosocial_remarks='High academic achiever. Has been studying 10–12 hours daily since freshman year. Dropped all extracurriculars. Sleep has deteriorated. Limited peer connection recently.',
    interaction_relationship=i('engaged','calm'), affect_expression=a('flat','appropriate'),
    interaction_remarks='Initially guarded — seemed uncertain why they came. Became more open when IC framed burnout as a legitimate concern rather than weakness.',
    maladaptive_patterns=m('academic_pat','avoidance','suppression'),
    counseling_goal='Within 6 sessions, client will identify and schedule at least 3 restorative activities weekly, establish a sustainable study schedule, and report improved engagement with academic content.',
    predisposing_factors=pre('personality'), precipitating_factors=pci('academic'),
    perpetuating_factors=per('stressors','self_care'), protective_factors=pro('social','motivation'),
    recommendation=rec('continue','follow_up')),

'CPS-2025-010': dict(  # Harold — social anxiety
    general_appearance=g('casual','tense','distress'), communication_style=c('hesitant','minimal'),
    general_disposition=d('anxious','resistant'),
    brief_description_remarks='Student avoided eye contact initially. Fidgety, hands shaking slightly. Engaged more as session normalized social anxiety. Clear discomfort with being observed.',
    presenting_problem=p('anxiety','self_esteem','academic'),
    presenting_problem_remarks='Significant distress in social and evaluative situations — particularly class recitations, group projects, and meeting new people. Avoidance has led to missed requirements. GAD-7: 14.',
    psychosocial_history=h('past_exp','peers','family','academic'),
    psychosocial_remarks='Describes being shy and quiet since childhood. Limited close friendships. Moved to Manila for university — adjustment has been difficult. No prior counseling. Parents unaware of the severity.',
    interaction_relationship=i('guarded','calm'), affect_expression=a('anxious','appropriate'),
    interaction_remarks='Session required slower pacing to build safety. Student gradually opened up when IC reduced evaluative pressure. Showed willingness to work on anxiety by end of session.',
    maladaptive_patterns=m('avoidance','neg_self','dependence'),
    counseling_goal='Within 10 sessions, client will engage in graduated exposure to social situations (starting with one-on-one peer interaction) and reduce GAD-7 score from 14 to below 8 while maintaining academic requirements.',
    predisposing_factors=pre('personality','attachment'), precipitating_factors=pci('transition','academic'),
    perpetuating_factors=per('maladaptive','neg_thinking'), protective_factors=pro('motivation','resources'),
    recommendation=rec('continue','follow_up')),

'CPS-2025-011': dict(  # Jessica — eating disorder
    general_appearance=g('neat','tired'), communication_style=c('hesitant','guarded' if False else 'minimal'),
    general_disposition=d('resistant','cooperative'),
    brief_description_remarks='Student appeared thin and pale. Well-groomed but visibly fatigued. Defensive when eating behaviors were discussed. Gradually became more engaged.',
    presenting_problem=p('self_esteem','depression'),
    presenting_problem_remarks='Referred by school nurse due to significant weight loss. Student minimizes — "I eat when I\'m hungry." BMI: 17.0. Amenorrhea for 2 months. Exercises 3 hours daily. Body image significantly disturbed.',
    psychosocial_history=h('family','past_exp','health','peers'),
    psychosocial_remarks='High family expectations around appearance. Prior history of dieting behaviors in high school. Close peer group but hiding eating behaviors from friends. No prior mental health treatment.',
    interaction_relationship=i('guarded','calm'), affect_expression=a('appropriate','flat'),
    interaction_remarks='Student was defensive initially, particularly around weight and eating. Became slightly more open when IC focused on functional impairment (fatigue, academic performance) rather than eating directly.',
    maladaptive_patterns=m('avoidance','neg_self','perfectionism','maladaptive_coping'),
    counseling_goal='Within 12 sessions, client will achieve medical stabilization (BMI ≥ 18.5), demonstrate engagement with meal plan adherence (minimum 80%), and identify 2 cognitive distortions about body image to challenge in session.',
    predisposing_factors=pre('personality','cultural','family_hx'), precipitating_factors=pci('academic','transition'),
    perpetuating_factors=per('neg_thinking','no_insight','self_care'), protective_factors=pro('motivation','resources','academic'),
    recommendation=rec('psych_tx','psychiatry','continue')),

'CPS-2025-012': dict(  # Priya — grief/bereavement
    general_appearance=g('casual','tired'), communication_style=c('expressive','hesitant'),
    general_disposition=d('sad','cooperative'),
    brief_description_remarks='Student appeared sad but composed. Teared up when discussing the loss. Maintained engagement throughout. Appropriately dressed.',
    presenting_problem=p('grief','depression','academic'),
    presenting_problem_remarks='Lost a close family member 6 weeks ago. Reports persistent sadness, withdrawal from friends, and declining academic attendance. Difficulty finding meaning or motivation. PHQ-9: 12.',
    psychosocial_history=h('family','past_exp','faith','peers'),
    psychosocial_remarks='Strong family bond. Death of family member was sudden and unexpected. Student has faith community but has avoided attending since the loss. Close friends have been supportive but student withdrawing.',
    interaction_relationship=i('warm','engaged'), affect_expression=a('depressed','appropriate'),
    interaction_remarks='Student was open and able to describe grief experience clearly. Rapport built naturally. Expressed relief at having a space to process without worrying about burdening friends.',
    maladaptive_patterns=m('avoidance','suppression'),
    counseling_goal='Within 6 sessions, client will engage in adaptive grieving, re-establish connection with at least 2 social supports, and return to baseline academic attendance (minimum 80%).',
    predisposing_factors=pre('attachment'), precipitating_factors=pci('loss'),
    perpetuating_factors=per('maladaptive','stressors'), protective_factors=pro('faith','social','motivation'),
    recommendation=rec('continue','follow_up')),

'CPS-2025-013': dict(  # Rachel — OCD symptoms
    general_appearance=g('neat','tense'), communication_style=c('clear','verbose'),
    general_disposition=d('anxious','cooperative'),
    brief_description_remarks='Student was punctual and well-groomed. Described symptoms in organized, detailed manner. Showed visible distress when describing intrusive thoughts.',
    presenting_problem=p('anxiety','self_esteem'),
    presenting_problem_remarks='Reports distressing intrusive thoughts (contamination-related) and compulsive checking behaviors (repeatedly checking locks, stove, academic submissions). Cycle takes 2–3 hours daily. Significant functional impairment.',
    psychosocial_history=h('family','academic','coping','past_exp'),
    psychosocial_remarks='Family history of anxiety. Student has had milder OCD symptoms since high school but significantly worsened this semester. Academic performance still intact but threatened. No prior treatment.',
    interaction_relationship=i('engaged','motivated'), affect_expression=a('anxious','appropriate'),
    interaction_remarks='Student was well-informed about OCD and had researched it themselves. Highly motivated to address symptoms. Expressed frustration at being "trapped" by rituals.',
    maladaptive_patterns=m('worry','avoidance','perfectionism'),
    counseling_goal='Within 12 sessions using ERP (Exposure and Response Prevention), client will reduce OCD ritual time from 2–3 hours to under 30 minutes/day, as measured by self-monitoring logs.',
    predisposing_factors=pre('family_hx','personality'), precipitating_factors=pci('academic','transition'),
    perpetuating_factors=per('maladaptive','neg_thinking'), protective_factors=pro('motivation','academic','social'),
    recommendation=rec('psych_tx','continue','follow_up')),

'CPS-2025-014': dict(  # Iris — ADHD/academic difficulties
    general_appearance=g('casual','relaxed'), communication_style=c('verbose','expressive'),
    general_disposition=d('cooperative','friendly'),
    brief_description_remarks='Student arrived 5 minutes late and apologized. Fidgeted throughout but engaged warmly. Tangential in responses — required gentle redirection. Good humor present.',
    presenting_problem=p('academic','self_esteem','anxiety'),
    presenting_problem_remarks='Longstanding difficulty sustaining attention, completing tasks before deadlines, and managing impulsivity. Reports feeling "lazy" and "stupid" despite knowing the material. GAD-7: 12 — linked to academic underperformance.',
    psychosocial_history=h('academic','family','coping','peers'),
    psychosocial_remarks='Describes history of being called "spacey" or "distracted" throughout school. Never formally evaluated. Family supportive but confused by inconsistent performance. Socially connected but academically struggling.',
    interaction_relationship=i('warm','engaged','motivated'), affect_expression=a('appropriate','anxious'),
    interaction_remarks='Student was engaging and personable. Showed insight into attention difficulties when given structure. Clearly motivated to understand and address challenges.',
    maladaptive_patterns=m('academic_pat','impulsivity','neg_self'),
    counseling_goal='Within 10 sessions, client will implement 3 organizational systems (time-blocking, task chunting, reminder apps), reduce missed academic deadlines from 4–5/semester to 1–2, and challenge negative self-narratives around intelligence.',
    predisposing_factors=pre('medical','personality'), precipitating_factors=pci('academic','transition'),
    perpetuating_factors=per('neg_thinking','self_care'), protective_factors=pro('social','motivation','academic'),
    recommendation=rec('psych_test','continue','follow_up')),

'CPS-2025-015': dict(  # Jake — stress/time management
    general_appearance=g('casual','tense'), communication_style=c('clear','expressive'),
    general_disposition=d('cooperative','anxious'),
    brief_description_remarks='Student appeared visibly rushed. Mentioned having two classes after the session. Engaged well despite time pressure. No acute distress.',
    presenting_problem=p('academic','anxiety'),
    presenting_problem_remarks='Law school demands significantly exceed student\'s current time management capacity. Reports chronic fatigue, falling behind on readings, and difficulty separating "law student" identity from personal life.',
    psychosocial_history=h('academic','coping','peers','health'),
    psychosocial_remarks='Chose law school with strong motivation. Good peer study group. Health and self-care deprioritized since enrollment. Sleep 4–5 hours nightly. Skipping meals frequently.',
    interaction_relationship=i('engaged','motivated'), affect_expression=a('anxious','appropriate'),
    interaction_remarks='Student engaged efficiently — adapted well to structured intake format. Showed good insight into the time management gap. Expressed clear motivation to develop strategies.',
    maladaptive_patterns=m('academic_pat','avoidance','self_care' if False else 'neg_self'),
    counseling_goal='Within 6 sessions, client will establish a sustainable weekly schedule that includes minimum 7 hours sleep, 3 self-care activities, and structured study blocks — resulting in reduced self-reported chronic fatigue.',
    predisposing_factors=pre('personality'), precipitating_factors=pci('academic','transition'),
    perpetuating_factors=per('stressors','self_care'), protective_factors=pro('social','motivation','academic'),
    recommendation=rec('continue','follow_up')),

'CPS-2025-016': dict(  # Carlos — bipolar disorder
    general_appearance=g('casual','tired'), communication_style=c('expressive','verbose'),
    general_disposition=d('cooperative','anxious'),
    brief_description_remarks='Student appeared somewhat elevated in energy compared to self-reported depressive state. Spoke rapidly at times. Referred by outpatient psychiatrist for supportive therapy.',
    presenting_problem=p('depression','anxiety'),
    presenting_problem_remarks='Known diagnosis of Bipolar Disorder Type I. Currently in depressive phase — sleeping 12–14 hours, missing classes. History of one manic episode requiring hospitalization 18 months ago. On lithium.',
    psychosocial_history=h('past_exp','family','health','prev_tx'),
    psychosocial_remarks='Psychiatric history since 2nd year. Family informed and involved. Has been in and out of psychiatric care. Motivated to maintain stability but struggles with medication side effects (weight gain, cognitive dulling).',
    interaction_relationship=i('engaged','warm'), affect_expression=a('appropriate','depressed'),
    interaction_remarks='Student was open about diagnosis and history. Showed good insight into illness pattern. Expressed concern about academic consequences during depressive phases.',
    maladaptive_patterns=m('academic_pat','maladaptive_coping'),
    counseling_goal='Within ongoing sessions (no fixed endpoint), client will maintain mood monitoring logs, adhere to psychiatric medication, develop 3 early warning sign responses, and sustain academic engagement during depressive phases.',
    predisposing_factors=pre('medical','family_hx'), precipitating_factors=pci('academic','transition'),
    perpetuating_factors=per('self_care','stressors'), protective_factors=pro('social','resources','faith','motivation'),
    recommendation=rec('collab','continue','follow_up')),

'CPS-2025-017': dict(  # Mia — homesickness/adjustment
    general_appearance=g('casual','relaxed'), communication_style=c('expressive','clear'),
    general_disposition=d('friendly','sad'),
    brief_description_remarks='Student was warmly dressed, appeared younger than age. Cried briefly when mentioning parents. Otherwise composed and engaged throughout.',
    presenting_problem=p('adjustment','grief','anxiety'),
    presenting_problem_remarks='First-year student from province experiencing significant homesickness. Reports loneliness despite living in dormitory with other students, difficulty connecting with peers, and missing family routines.',
    psychosocial_history=h('family','peers','faith','academic'),
    psychosocial_remarks='Very close-knit family from Visayas. First time living away from home. Has tried joining organizations but feels "out of place." Faith is an important anchor. Academic performance adequate but trending down.',
    interaction_relationship=i('warm','engaged'), affect_expression=a('depressed','appropriate'),
    interaction_remarks='Student connected easily with IC. Expressed significant relief at being heard. Showed good self-awareness about adjustment difficulties.',
    maladaptive_patterns=m('avoidance','suppression'),
    counseling_goal='Within 6 sessions, client will establish 2 consistent social connections in university, develop a weekly structure that includes both academic and social activities, and reduce homesickness intensity from daily to manageable episodes.',
    predisposing_factors=pre('attachment','cultural'), precipitating_factors=pci('transition'),
    perpetuating_factors=per('maladaptive','environment'), protective_factors=pro('faith','motivation','academic'),
    recommendation=rec('continue','follow_up')),

'CPS-2025-018': dict(  # Leo — substance use/alcohol
    general_appearance=g('casual','relaxed'), communication_style=c('clear','hesitant'),
    general_disposition=d('cooperative','resistant'),
    brief_description_remarks='Student appeared well and did not show signs of intoxication. Initially minimized alcohol use. Became more honest as session progressed.',
    presenting_problem=p('substance','anxiety','academic'),
    presenting_problem_remarks='Acknowledges drinking 5–6 nights/week since semester began — "just to relax." Reports blackout episodes twice in the past month. Starting to affect morning academic attendance.',
    psychosocial_history=h('past_exp','peers','health','substance'),
    psychosocial_remarks='Family history of alcohol use (father). Peer group normalizes heavy drinking. Has had 2 episodes of risky behavior while intoxicated. No prior counseling or substance treatment.',
    interaction_relationship=i('guarded','engaged'), affect_expression=a('appropriate','anxious'),
    interaction_remarks='Student was initially guarded about disclosing amounts. Motivational interviewing approach worked well — student identified autonomy-based reasons to reduce use by end of session.',
    maladaptive_patterns=m('maladaptive_coping','avoidance','impulsivity'),
    counseling_goal='Within 8 sessions, client will reduce alcohol consumption to weekend-only, no blackout episodes, and identify 3 healthy coping alternatives for academic stress using MI-informed approach.',
    predisposing_factors=pre('family_hx','personality'), precipitating_factors=pci('academic','transition'),
    perpetuating_factors=per('stressors','maladaptive'), protective_factors=pro('motivation','academic'),
    recommendation=rec('psych_tx','continue','follow_up')),

'CPS-2025-019': dict(  # Ola — pending termination/academic stress
    general_appearance=g('neat','relaxed'), communication_style=c('clear','expressive'),
    general_disposition=d('cooperative','friendly'),
    brief_description_remarks='Student appeared well, calm, and notably more relaxed compared to initial intake. Clear positive change from beginning of treatment.',
    presenting_problem=p('academic','anxiety'),
    presenting_problem_remarks='At intake: academic pressure and mild anxiety. Now at termination stage. PHQ-9 reduced from 10 to 3. Student reports consistent use of coping strategies.',
    psychosocial_history=h('academic','coping','peers'),
    psychosocial_remarks='Strong academic foundation. Good peer support. Coping strategies have improved significantly over the course of treatment.',
    interaction_relationship=i('warm','engaged','motivated'), affect_expression=a('euthymic','appropriate'),
    interaction_remarks='Student was reflective about growth during treatment. Expressed confidence in maintaining gains independently.',
    maladaptive_patterns=m('none'),
    counseling_goal='Maintain gains achieved in therapy. No further active counseling goals — transitioning to self-monitoring.',
    predisposing_factors=pre('personality'), precipitating_factors=pci('academic'),
    perpetuating_factors=per('neg_thinking'), protective_factors=pro('motivation','social','academic'),
    recommendation=rec('follow_up')),

'CPS-2025-020': dict(  # Amy — pending termination/grief
    general_appearance=g('neat','relaxed'), communication_style=c('clear','expressive'),
    general_disposition=d('cooperative','calm'),
    brief_description_remarks='Student appeared composed and peaceful. Significant improvement since initial presentation. Ready for discharge discussion.',
    presenting_problem=p('grief'),
    presenting_problem_remarks='At intake: grief following loss. Now resolved. Client has processed loss and returned to baseline functioning. Academic performance restored.',
    psychosocial_history=h('family','peers','faith'),
    psychosocial_remarks='Strong family support. Faith community re-engaged. Peer relationships fully restored.',
    interaction_relationship=i('warm','engaged'), affect_expression=a('euthymic','appropriate'),
    interaction_remarks='Student was positive and reflective. Expressed gratitude for counseling support. Clear readiness to terminate.',
    maladaptive_patterns=m('none'),
    counseling_goal='Maintain adaptive grieving and coping skills developed in therapy.',
    predisposing_factors=pre('attachment'), precipitating_factors=pci('loss'),
    perpetuating_factors=per('maladaptive'), protective_factors=pro('faith','social','motivation'),
    recommendation=rec('follow_up')),

'CPS-2025-021': dict(  # Paz — pending termination/depression
    general_appearance=g('neat','casual'), communication_style=c('clear','expressive'),
    general_disposition=d('cooperative','friendly'),
    brief_description_remarks='Student appeared much improved from initial intake. Energy level noticeably better. Confident tone.',
    presenting_problem=p('depression'),
    presenting_problem_remarks='At intake: mild-moderate depression (PHQ-9: 11). Now at step-down stage (PHQ-9: 6). Functioning restored.',
    psychosocial_history=h('academic','peers','family'),
    psychosocial_remarks='Academic and social functioning restored. Family relationships improved. Peer support network active.',
    interaction_relationship=i('warm','motivated'), affect_expression=a('euthymic','appropriate'),
    interaction_remarks='Student was engaged and optimistic. Demonstrated good insight into relapse prevention strategies.',
    maladaptive_patterns=m('none'),
    counseling_goal='Consolidate therapy gains. Continue self-monitoring using PHQ-9 monthly.',
    predisposing_factors=pre('family_hx'), precipitating_factors=pci('academic'),
    perpetuating_factors=per('neg_thinking'), protective_factors=pro('social','motivation','academic'),
    recommendation=rec('follow_up')),

'CPS-2025-022': dict(  # Rex — closed/adjustment
    general_appearance=g('neat','relaxed'), communication_style=c('clear','expressive'),
    general_disposition=d('cooperative','friendly'),
    brief_description_remarks='Student at termination was well-adjusted, composed, and positive. Clear growth from initial presentation of homesickness and adjustment difficulties.',
    presenting_problem=p('adjustment','anxiety'),
    presenting_problem_remarks='Initial intake: first-year adjustment difficulty. Treatment goals fully met after 6 sessions.',
    psychosocial_history=h('family','peers','academic'),
    psychosocial_remarks='Strong family support. Has built meaningful peer connections at university. Academic performance stable.',
    interaction_relationship=i('warm','engaged'), affect_expression=a('euthymic','appropriate'),
    interaction_remarks='Excellent rapport throughout treatment. Student showed remarkable resilience and openness to change.',
    maladaptive_patterns=m('none'),
    counseling_goal='(Achieved) Build university social connections and develop independence skills.',
    predisposing_factors=pre('attachment'), precipitating_factors=pci('transition'),
    perpetuating_factors=per('maladaptive'), protective_factors=pro('social','faith','motivation'),
    recommendation=rec('follow_up')),

'CPS-2025-023': dict(  # Sofia — closed/anxiety/panic
    general_appearance=g('neat','relaxed'), communication_style=c('clear','expressive'),
    general_disposition=d('cooperative','friendly'),
    brief_description_remarks='At final session: student appeared calm and confident. No panic symptoms observed. Significant improvement from initial intake where visible anxiety was present.',
    presenting_problem=p('anxiety'),
    presenting_problem_remarks='Initial intake: panic disorder with 3–4 panic attacks/week. At closure: panic-free for 8 consecutive weeks. PHQ-9: 5 (was 12).',
    psychosocial_history=h('academic','family','coping'),
    psychosocial_remarks='Strong academic engagement throughout treatment. Family supportive. Coping toolkit well-developed.',
    interaction_relationship=i('warm','motivated'), affect_expression=a('euthymic','appropriate'),
    interaction_remarks='Student consistently engaged, implemented all homework tasks, and built genuine competence in anxiety management.',
    maladaptive_patterns=m('none'),
    counseling_goal='(Achieved) Reduce panic frequency to zero. Maintain gains through relapse prevention plan.',
    predisposing_factors=pre('personality','family_hx'), precipitating_factors=pci('academic'),
    perpetuating_factors=per('neg_thinking'), protective_factors=pro('motivation','social','academic'),
    recommendation=rec('follow_up')),

'CPS-2025-024': dict(  # Nina — closed/SI depression
    general_appearance=g('disheveled','tired'), communication_style=c('minimal','hesitant'),
    general_disposition=d('sad','resistant'),
    brief_description_remarks='At intake: student presented in crisis — disheveled, tearful, minimally communicative. Emergency protocol required. Now closed with external psychiatric referral.',
    presenting_problem=p('depression','self_esteem'),
    presenting_problem_remarks='Severe depression with SI at intake (PHQ-9: 25). Stabilized through crisis intervention and psychiatric hospitalization. Transferred to NCMH outpatient for ongoing care.',
    psychosocial_history=h('past_exp','family','health'),
    psychosocial_remarks='History of depressive episodes since early adolescence. Family conflict ongoing. Hospitalized once prior to CPS engagement. Psychiatric follow-up now established.',
    interaction_relationship=i('withdrawn','guarded'), affect_expression=a('depressed','flat'),
    interaction_remarks='Initially required significant patience to engage. Crisis was managed with empathy and clear protocol. Student expressed gratitude for intervention before referral.',
    maladaptive_patterns=m('avoidance','neg_self','suppression','trauma_resp'),
    counseling_goal='(Achieved at CPS level) Safety stabilization. Ongoing care transferred to NCMH outpatient psychiatric services.',
    predisposing_factors=pre('family_hx','early_adv'), precipitating_factors=pci('loss','academic'),
    perpetuating_factors=per('environment','neg_thinking'), protective_factors=pro('resources'),
    recommendation=rec('crisis','psychiatry','external')),

'CPS-2025-025': dict(  # Sara — closed/stress/depression
    general_appearance=g('neat','relaxed'), communication_style=c('clear','expressive'),
    general_disposition=d('cooperative','friendly'),
    brief_description_remarks='At final session: student appeared vibrant and engaged. Strong contrast from initial intake where significant fatigue and low mood were present.',
    presenting_problem=p('depression','academic'),
    presenting_problem_remarks='Initial: mild-moderate depression (PHQ-9: 14). At closure: PHQ-9: 4. Academic performance restored to honors level.',
    psychosocial_history=h('academic','coping','peers'),
    psychosocial_remarks='Strong peer support. Academic engagement fully restored. Self-care routines well-established.',
    interaction_relationship=i('warm','motivated'), affect_expression=a('euthymic','appropriate'),
    interaction_remarks='Excellent therapeutic alliance throughout. Student was model of engagement and commitment to recovery.',
    maladaptive_patterns=m('none'),
    counseling_goal='(Achieved) Reduce depressive symptoms and restore academic functioning.',
    predisposing_factors=pre('personality'), precipitating_factors=pci('academic'),
    perpetuating_factors=per('self_care'), protective_factors=pro('social','motivation'),
    recommendation=rec('follow_up')),

'CPS-2025-026': dict(  # Tim — closed/family/self-esteem
    general_appearance=g('neat','relaxed'), communication_style=c('clear','expressive'),
    general_disposition=d('cooperative','calm'),
    brief_description_remarks='At final session: student appeared confident and articulate. Clear growth in assertiveness and boundary-setting since initial intake.',
    presenting_problem=p('relationship','self_esteem'),
    presenting_problem_remarks='Initial: family conflict and low self-esteem. At closure: healthier family boundaries established. Self-esteem scale improved from 14 to 26/30.',
    psychosocial_history=h('family','peers','coping'),
    psychosocial_remarks='Family dynamics significantly improved. Peer relationships stable. Assertiveness skills well-developed.',
    interaction_relationship=i('warm','engaged'), affect_expression=a('euthymic','appropriate'),
    interaction_remarks='Student showed consistent growth. Demonstrated assertiveness skills in session through confident communication.',
    maladaptive_patterns=m('none'),
    counseling_goal='(Achieved) Develop assertiveness and healthy family boundaries.',
    predisposing_factors=pre('attachment','family_hx'), precipitating_factors=pci('relationship'),
    perpetuating_factors=per('neg_thinking'), protective_factors=pro('social','motivation'),
    recommendation=rec('follow_up')),

'CPS-2025-027': dict(  # Grace — closed/trauma
    general_appearance=g('neat','relaxed'), communication_style=c('clear','expressive'),
    general_disposition=d('calm','cooperative'),
    brief_description_remarks='At final session: student appeared grounded and peaceful. Strong contrast from initial presentation of hypervigilance and avoidance.',
    presenting_problem=p('trauma','anxiety'),
    presenting_problem_remarks='Initial: PTSD following history of abuse. PCL-5: 52 at intake. At closure: PCL-5: 12 — remission. Completed 16-session trauma protocol.',
    psychosocial_history=h('past_exp','family','faith','coping'),
    psychosocial_remarks='Has built strong support network. Faith community active. Family supportive of recovery journey.',
    interaction_relationship=i('warm','motivated'), affect_expression=a('euthymic','appropriate'),
    interaction_remarks='Student showed exceptional courage throughout trauma-focused therapy. Demonstrated remarkable resilience and growth.',
    maladaptive_patterns=m('none'),
    counseling_goal='(Achieved) PTSD in remission. Community support group referral provided.',
    predisposing_factors=pre('early_adv'), precipitating_factors=pci('trauma'),
    perpetuating_factors=per('environment'), protective_factors=pro('faith','social','motivation','coping'),
    recommendation=rec('external','follow_up')),

'CPS-2025-028': dict(  # Uma — closed/burnout
    general_appearance=g('neat','relaxed'), communication_style=c('clear','expressive'),
    general_disposition=d('friendly','cooperative'),
    brief_description_remarks='At final session: student appeared energized and engaged. Burnout symptoms fully resolved. Academic engagement restored.',
    presenting_problem=p('academic'),
    presenting_problem_remarks='Initial: academic burnout. At closure: student has implemented sustainable academic routines. Teaching internship performance excellent.',
    psychosocial_history=h('academic','coping','peers','health'),
    psychosocial_remarks='Self-care routines established. Peer support active. Sleep and exercise normalized.',
    interaction_relationship=i('warm','motivated'), affect_expression=a('euthymic','appropriate'),
    interaction_remarks='Student was engaged and proactive in implementing strategies. Showed genuine insight into burnout patterns.',
    maladaptive_patterns=m('none'),
    counseling_goal='(Achieved) Establish sustainable academic routines and self-care practices.',
    predisposing_factors=pre('personality'), precipitating_factors=pci('academic'),
    perpetuating_factors=per('self_care'), protective_factors=pro('social','motivation'),
    recommendation=rec('follow_up')),

'CPS-2025-029': dict(  # Sam — closed/severe anxiety
    general_appearance=g('tense','casual'), communication_style=c('hesitant','minimal'),
    general_disposition=d('anxious','resistant'),
    brief_description_remarks='At intake: student appeared highly anxious, avoided open spaces in clinic, required session in smaller room. Referred externally as CPS services insufficient for severity.',
    presenting_problem=p('anxiety'),
    presenting_problem_remarks='Severe agoraphobia with panic disorder. Housebound for 3 weeks prior to referral. PHQ-9: 19, GAD-7: 18. Requires intensive outpatient or day hospital treatment.',
    psychosocial_history=h('past_exp','health','family','prev_tx'),
    psychosocial_remarks='Prior mild anxiety history that escalated suddenly. No family history of mental illness. Parents concerned but uncertain how to help. Brief trial of SSRIs 2 years ago discontinued.',
    interaction_relationship=i('guarded','calm'), affect_expression=a('anxious','appropriate'),
    interaction_remarks='Required significant accommodation during intake. Student managed to complete despite visible distress. Accepted external referral with relief.',
    maladaptive_patterns=m('avoidance','worry','maladaptive_coping'),
    counseling_goal='(CPS level closed) Referred to private psychiatrist for intensive outpatient treatment of agoraphobia with panic disorder.',
    predisposing_factors=pre('medical','personality'), precipitating_factors=pci('health'),
    perpetuating_factors=per('maladaptive','environment'), protective_factors=pro('social','resources'),
    recommendation=rec('psychiatry','external')),

'CPS-2025-030': dict(  # Vince — closed/grief
    general_appearance=g('neat','casual'), communication_style=c('expressive','clear'),
    general_disposition=d('sad','cooperative'),
    brief_description_remarks='At final session: student appeared peaceful and resolved. Grief integration complete. Academic functioning restored.',
    presenting_problem=p('grief','depression'),
    presenting_problem_remarks='Initial: grief following loss of grandparent and academic decline. At closure: grief processed, academic GPA restored, meaningful rituals established.',
    psychosocial_history=h('family','faith','peers'),
    psychosocial_remarks='Family gathered and healed together around the loss. Faith provided structure for grief. Peer support maintained throughout.',
    interaction_relationship=i('warm','engaged'), affect_expression=a('euthymic','appropriate'),
    interaction_remarks='Beautiful therapeutic process — student moved from acute grief to meaningful integration. Showed great courage in facing loss.',
    maladaptive_patterns=m('none'),
    counseling_goal='(Achieved) Process grief and restore academic functioning.',
    predisposing_factors=pre('attachment'), precipitating_factors=pci('loss'),
    perpetuating_factors=per('maladaptive'), protective_factors=pro('faith','social','motivation'),
    recommendation=rec('follow_up')),

'CPS-2025-031': dict(  # Vince Dela Cruz — new/social anxiety
    general_appearance=g('casual','tense'), communication_style=c('hesitant','minimal'),
    general_disposition=d('anxious','resistant'),
    brief_description_remarks='Student referred by faculty due to class absences. Initially reluctant to engage. Gradually opened up when given control over pace of session.',
    presenting_problem=p('anxiety','academic','self_esteem'),
    presenting_problem_remarks='Significant social anxiety — avoids class recitations, group activities, and peer interactions. Has missed 6 of the last 10 class sessions. GAD-7: 16.',
    psychosocial_history=h('past_exp','peers','family','academic'),
    psychosocial_remarks='Quiet and withdrawn since high school. Parents unaware of severity. No close friendships at university. Academic performance was strong until this semester.',
    interaction_relationship=i('guarded','calm'), affect_expression=a('anxious','appropriate'),
    interaction_remarks='Required patient, low-pressure approach. Student became more comfortable as session progressed. Agreed to return for counseling.',
    maladaptive_patterns=m('avoidance','neg_self'),
    counseling_goal='Within 10 sessions, client will attend all class sessions, engage in at least one social activity per week, and reduce GAD-7 from 16 to below 8.',
    predisposing_factors=pre('personality','attachment'), precipitating_factors=pci('academic','transition'),
    perpetuating_factors=per('maladaptive','neg_thinking'), protective_factors=pro('motivation','resources'),
    recommendation=rec('continue','follow_up')),

'CPS-2025-032': dict(  # Maria Santos — new/self-harm
    general_appearance=g('disheveled','tired','distress'), communication_style=c('minimal','hesitant'),
    general_disposition=d('sad','resistant'),
    brief_description_remarks='Student presented via friend referral. Visible distress. Wearing long sleeves (examination of forearms deferred to clinical setting). Emergency protocol reviewed.',
    presenting_problem=p('depression','self_esteem','trauma'),
    presenting_problem_remarks='Friend disclosed that student has been self-harming (superficial cuts on forearms). Student acknowledged this in session. PHQ-9: 24. No current SI but history of passive ideation.',
    psychosocial_history=h('past_exp','family','peers','health'),
    psychosocial_remarks='History of emotional neglect in childhood. Parents are emotionally unavailable. Student has one close friend who made the referral. No prior counseling.',
    interaction_relationship=i('withdrawn','guarded'), affect_expression=a('depressed','flat'),
    interaction_remarks='Student was extremely guarded. Took 15 minutes of gentle rapport-building before any disclosure. Once trusting, showed significant pain and desire for help.',
    maladaptive_patterns=m('avoidance','neg_self','maladaptive_coping','suppression'),
    counseling_goal='Immediate safety assessment and stabilization. Within 4 sessions, establish therapeutic alliance and safety plan. Reduce self-harm frequency and intensity with DBT-informed approach.',
    predisposing_factors=pre('early_adv','attachment','family_hx'), precipitating_factors=pci('academic','loss'),
    perpetuating_factors=per('environment','neg_thinking','no_insight'), protective_factors=pro('motivation','resources'),
    recommendation=rec('crisis','psych_tx','psychiatry')),

'CPS-2025-033': dict(  # Ethan Lee — new/exam anxiety
    general_appearance=g('neat','tense'), communication_style=c('clear','expressive'),
    general_disposition=d('anxious','cooperative'),
    brief_description_remarks='Student was punctual and well-prepared — brought a list of symptoms to describe. Clearly motivated to address exam anxiety before board exams.',
    presenting_problem=p('anxiety','academic'),
    presenting_problem_remarks='Significant test anxiety — mind goes blank during exams despite thorough preparation. GAD-7: 13. Board exams in 8 weeks. Sleep disrupted before exam nights.',
    psychosocial_history=h('academic','coping','peers'),
    psychosocial_remarks='High academic performer with consistent anxiety around examinations. Good peer study group. No prior counseling. Copes through over-preparation and caffeine.',
    interaction_relationship=i('engaged','motivated'), affect_expression=a('anxious','appropriate'),
    interaction_remarks='Student was proactive and organized. Excellent candidate for structured anxiety intervention. Highly motivated with clear timeline.',
    maladaptive_patterns=m('worry','avoidance','perfectionism'),
    counseling_goal='Within 8 sessions before board exams, client will reduce GAD-7 from 13 to below 8, implement exam-day anxiety management protocol, and complete practice exams without blanking.',
    predisposing_factors=pre('personality'), precipitating_factors=pci('academic'),
    perpetuating_factors=per('neg_thinking','self_care','maladaptive'), protective_factors=pro('social','motivation','academic'),
    recommendation=rec('continue','follow_up')),

'CPS-2025-034': dict(  # Diana Santos — new/depression
    general_appearance=g('casual','tired'), communication_style=c('hesitant','flat'),
    general_disposition=d('cooperative','sad'),
    brief_description_remarks='Student appeared visibly low in energy and affect. Self-referred after one month of persistent low mood. No acute crisis but PHQ-9 elevated.',
    presenting_problem=p('depression','self_esteem','academic'),
    presenting_problem_remarks='Reports persistent low mood, loss of interest in activities, fatigue, and increased social isolation for past 4 weeks. PHQ-9: 14. Academic attendance declining.',
    psychosocial_history=h('past_exp','family','peers','coping'),
    psychosocial_remarks='Previously socially active and engaged. Family relationships strained recently after parental separation. Peer withdrawal progressive over the past month. Coping through sleep.',
    interaction_relationship=i('engaged','guarded'), affect_expression=a('depressed','appropriate'),
    interaction_remarks='Student was somewhat guarded but engaged when given space to process at own pace. Showed insight into connection between social withdrawal and low mood.',
    maladaptive_patterns=m('avoidance','suppression','neg_self'),
    counseling_goal='Within 8 sessions, client will reduce PHQ-9 from 14 to below 8, re-engage in minimum 2 social activities weekly, and maintain academic attendance above 80%.',
    predisposing_factors=pre('family_hx','attachment'), precipitating_factors=pci('relationship','academic'),
    perpetuating_factors=per('maladaptive','stressors'), protective_factors=pro('motivation','resources'),
    recommendation=rec('continue','follow_up')),

'CPS-2025-035': dict(  # Kevin Lim — new/eating disorder
    general_appearance=g('neat','tired'), communication_style=c('hesitant','minimal'),
    general_disposition=d('resistant','cooperative'),
    brief_description_remarks='Student referred by school nurse due to significant weight loss. Appeared thin, pale, mildly defensive about eating behaviors. BMI: 16.8.',
    presenting_problem=p('self_esteem','depression'),
    presenting_problem_remarks='Significant dietary restriction — consuming approximately 600–800 kcal/day. Exercises 2 hours daily. Reports intense fear of weight gain. BMI: 16.8 — medical monitoring required.',
    psychosocial_history=h('family','past_exp','health','peers'),
    psychosocial_remarks='Competitive academic environment. Comments about weight from peers 6 months ago. Family history of controlling eating behaviors in parent. No prior mental health treatment.',
    interaction_relationship=i('guarded','calm'), affect_expression=a('flat','appropriate'),
    interaction_remarks='Student minimized severity initially. Motivational interviewing approach allowed some ambivalence to surface. Agreed to medical evaluation as first step.',
    maladaptive_patterns=m('avoidance','perfectionism','neg_self','maladaptive_coping'),
    counseling_goal='Immediate medical stabilization. Within 4 sessions, establish therapeutic alliance and begin nutritional rehabilitation. Target BMI ≥ 18.5 within 3 months with medical and CPS coordination.',
    predisposing_factors=pre('family_hx','personality','cultural'), precipitating_factors=pci('academic','health'),
    perpetuating_factors=per('neg_thinking','no_insight','self_care'), protective_factors=pro('motivation','resources'),
    recommendation=rec('psych_tx','psychiatry','crisis')),
}

# ── Apply enrichments ────────────────────────────────────────────────────────
updated = 0
for case_num, fields in ENRICHMENTS.items():
    update_fields = {f'intake_interview_form.{k}': v for k, v in fields.items()}
    result = db.cases.update_one({'case_number': case_num}, {'$set': update_fields})
    if result.modified_count:
        updated += 1

print(f"✅ Enriched {updated}/{len(ENRICHMENTS)} cases with full IC interview form data")

# Verify
sample = db.cases.find_one({'case_number': 'CPS-2025-001'})
form = sample.get('intake_interview_form', {})
fields_present = [f for f in ['general_appearance','communication_style','presenting_problem','psychosocial_history','interaction_relationship','maladaptive_patterns','counseling_goal','predisposing_factors','recommendation'] if f in form]
print(f"   Sample CPS-2025-001 has {len(fields_present)}/9 key IC form fields: {', '.join(fields_present)}")
